# Toetssystemen

## Veelgebruikte toetssystemen voor onderwijs

Dit hoofdstuk geeft een overzicht van veel gebruikte systemen om digitale toetsen af te nemen. Over het algemeen zijn het SaaS-oplossingen (een licentiemodel waarbij de software wordt aangeboden via het internet). 
Onderstaande lijst is samengesteld door experts die betrokken zijn bij het schrijven van dit handboek. De markt van toetssysteemleveranciers is dynamisch. Daarom is deze lijst niet compleet.

**Veel gebruikte generieke toetssystemen in Nederland:**
Dit zijn systemen die geschikt zijn voor grootschalige digitale toetsing, die vooral worden ingezet voor het afnemen van multiple choice vragen, gesloten vragen en korte essay vragen. Deze systemen bieden de mogelijkheid om toetsvragen (in samenwerking) te ontwikkelen, op te slaan in een itembank, toetsen af te nemen en psychometrische gegevens van de toetsvragen te verzamelen. 
-   [TestVision](http://www.testvision.nl)
-   [RemindoToets](https://www.paragin.nl/remindotoets/)
-   [MapleTA](https://www.maplesoft.com/products/mapleta/)
-   [Cirrus Assessment](http://www.cirrusassessment.com/)
-   [QM](http://www.questionmark.com)
-   [iQualify](https://www.iqualify.com)
-   [Ans Delft](https://www.ans.app)

**Toetssystemen in Learning Management Systemen (LMS):**
Verschillende LMS'en bieden toetssystemen aan. De itembankfunctie van deze systemen is beperkt. Ze zijn goed in te zetten voor formatieve toetsen, maar minder geschikt voor summatieve toetsen, vanwege de beperktere mogelijkheden tot beveiliging.

-   [Canvas](https://www.instructure.com/nl/canvas)
-   [Blackboard/Anthology](https://www.anthology.com/en-emea)
-   [Desire2Learn BrightSpace](https://www.d2l.com/nl/)
-   [Moodle](https://moodle.com/)
-   [Cumlaude](https://www.cumlaudelearning.com/)

**Itembanksystemen.:** 
Dit zijn losstaande applicaties om je toetsvragen te beheren, met de mogelijkheid om deze te exporteren en te gebruiken in anderen applicaties. 

-   [Respondus](https://www.respondus.com/)
-   [ExamView](https://www.turningtechnologies.com/examview)

**Toetssystemen met vragen:**
Deze systemen bieden toetsvragen aan en leveren hierbij een standaardsysteem om de vragen af te nemen. Deze systemen worden vaak ingezet voor formatieve toetsing.

-   [SOWISO (Wiskunde)](https://sowiso.nl/nl/)
-   [Grasple (Statistiek)](https://www.grasple.com/)
-   [R/Exams (Statistiek)](http://www.r-exams.org/)
-   [Drillster](https://www.drillster.com/info/)
-   [Quizlet](https://quizlet.com/)
-   [ProProfs](https://www.proprofs.com/)
-   Itembanken van uitgeverijen, vaak behorende bij een specifiek studieboek of online leeromgeving (bijv. [Pearson MyLab series](https://mlm.pearson.com/), (McGraw Hill methoden, WebAssign e.d.)
:::
