project:
  type: book

book:
  title: "Handboek Digitaal Toetsen"
  chapters:
    - index.qmd
    - 02-randvoorwaarden.qmd
    - 03-toetsvormen.qmd
    - 04-toetssystemen.qmd
    - 05-itembanken.qmd
    - 06-veilig-digitaal-toetsen.qmd
    - 07-innovaties.qmd
    - 08-colofon.qmd
 
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

