project:
  type: book
  output-dir: docs

book:
  title: "Handboek Digitaal Toetsen"
  chapters:
    - index.qmd
    - 02-randvoorwaarden.qmd
    - 03-toetsvormen.qmd
    - 04-toetssystemen.qmd
    - 05-toetsstandaarden.qmd
    - 06-toetsgegevens.qmd
    - 07-itembanken.qmd
    - 08-veilig-digitaal-toetsen.qmd
    - 09-innovaties.qmd
    - 10-begrippen.qmd
    - 11-colofon.qmd
    - 12-bijlagen.qmd
 
bibliography: references.bib

format:
  html:
    theme: journal
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreprt

editor: visual

number-depth: 3