# Introductie

Het handboek digitaal toetsen vloeit voort uit het [handboek itembanken](https://werkgroep-toetsen-op-afstand.github.io/Handboek-Itembanken/), dat door SURF en de Special Interest Group Digitaal Toetsen in 2018 is ontwikkeld. Bij de revisie in 2022 kwamen we al snel tot de conclusie dat het handboek itembanken eigenlijk veel meer omvatte dan alleen de basis voor het opstellen van itembanken. Zo bevatte het document al een begrippenkader, een overzicht van toetsvormen en een beschrijving van de toetscyclus. Daarom is besloten om het handboek itembanken uit te breiden en om te dopen tot het handboek digitaal toetsen. 

Het is onze intentie om het handboek regelmatig te updaten en uit te breiden. We nodigen iedereen uit om bij te dragen aan de inhoud van het handboek. Dit kan door feedback te geven op de bestaande inhoud, door nieuwe onderwerpen aan te dragen of door zelf een paragraaf of hoofdstuk te schrijven. We hosten het handboek op GitHub, zodat iedereen eenvoudig kan bijdragen.

## Inleiding

Het handboek digitaal toetsen is bedoeld voor onderwijsontwikkelaars, beleidmakers, toetsdeskundigen, applicatiebeheerders en geïnteresseerden die aan de slag willen met digitaal toetsen. In de hoofdstukken behandelen we eerst de randvoorwaarden die nodig zijn voor een goede inzet van digitaal toetsen. We verwijzen naar tools die kunnen helpen bij het formuleren van een eigen visie op toetsen en bij het bepalen van de huidige stand van zaken binnen de instelling. Vervolgens gaan we in op de verschillende toetsvormen die digitaal kunnen worden afgenomen. We beschrijven de voor- en nadelen van de verschillende toetsvormen.

We bespreken de verschillende toetssystemen die beschikbaar zijn en geven een overzicht van de verschillende standaarden die van belang zijn bij het uitwisselen van toetsmateriaal. We bespreken de verschillende toetsgegevens die toetsapplicaties kunnen leveren en natuurlijk hoe men een eigen itembank kan opzetten. In de laatste hoofdstukken gaan we in op de veiligheid rond digitaal toetsen en bespreken we verschillende innovaties die de toekomst van digitaal toetsen kunnen beïnvloeden.

We hopen met deze levende uitgave de bron te kunnen vormen voor alles wat gerelateerd is aan digitaal toetsen.
